# Each route describes how incoming requests are processed by platform.sh

"https://{default}/":
  type: upstream
  upstream: "ll_project:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"